-- [[ THINGS TO CHECK BEFORE FINISHING GAME:
-- ALL VALUES ARE TO THEIR CORRECT VALUES - FIX TESTING VALUES
-- MAKE SURE THERE ARE NO BUGS
-- IS EVERYTHING OPTIMIZED?




-- FIX TEAMS
-- TRACK PLAYERS IN ROUND
-- CREATE GLOBAL LEADERBOARDS
-- CREATE RANKING SYSTEM